number of parameters: 11.88M
Traceback (most recent call last):
  File "c:\Users\delfi\Desktop\MMI\DI725\DI725-main\DI725-main\assignment_1\sentiment_train.py", line 63, in <module>
    val_dataset = SentimentDataset('data/customer_service/val_split.csv',
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\delfi\Desktop\MMI\DI725\DI725-main\DI725-main\assignment_1\sentiment_dataset.py", line 9, in __init__
    self.data = pd.read_csv(csv_file)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delfi\anaconda3\envs\normal\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delfi\anaconda3\envs\normal\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delfi\anaconda3\envs\normal\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delfi\anaconda3\envs\normal\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\delfi\anaconda3\envs\normal\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/customer_service/val_split.csv'
